# The telemetry section defines parameters for Hermes' built-in telemetry capabilities. Global section has parameters that apply globally to the relayer operation.
[global]

# Specify the verbosity for the relayer logging output. Default: 'info'
# Valid options are 'error', 'warn', 'info', 'debug', 'trace'.
log_level = 'info'


# Specify the mode to be used by the relayer. [Required]
[mode]

# Specify the client mode.
[mode.clients]
# Whether or not to enable the client workers. [Required]
enabled = false
# Whether or not to enable periodic refresh of clients. [Default: false]
refresh = false
# Whether or not to enable misbehaviour detection for clients. [Default: false]
misbehaviour = false

# Specify the connections mode.
[mode.connections]
# Whether or not to enable the connection workers. [Required]
enabled = false

# Specify the channels mode.
[mode.channels]
# Whether or not to enable the channel workers. [Required]
enabled = false

# Specify the packets mode.
[mode.packets]
# Whether or not to enable the packet workers. [Required]
enabled = true
# Parametrize the periodic packet clearing feature.
# Interval (in number of blocks) at which pending packets
# should be eagerly cleared. A value of '0' will disable
# periodic packet clearing. [Default: 100]
clear_interval = 200
# Whether or not to clear packets on start. [Default: false]
clear_on_start = true
# Enable or disable the filtering mechanism.
# Valid options are 'true', 'false'.
# Currently Hermes supports two filters:
# 1. Packet filtering on a per-chain basis; see the chain-specific
#   filter specification below in [chains.packet_filter].
# 2. Filter for all activities based on client state trust threshold; this filter
#   is parametrized with (numerator = 1, denominator = 3), so that clients with
#   thresholds different than this will be ignored.
# If set to 'true', both of the above filters will be enabled.
# [Default: false]
filter = true
# Toggle the transaction confirmation mechanism.
# The tx confirmation mechanism periodically queries the `/tx_search` RPC
# endpoint to check that previously-submitted transactions
# (to any chain in this config file) have delivered successfully.
# Experimental feature. Affects telemetry if set to false.
# [Default: true]
tx_confirmation = false

# The REST section defines parameters for Hermes' built-in RESTful API.
# https://hermes.informal.systems/rest.html
[rest]

# Whether or not to enable the REST service. Default: false
enabled = true

# Specify the IPv4/6 host over which the built-in HTTP server will serve the RESTful
# API requests. Default: 127.0.0.1
host = '127.0.0.1'

# Specify the port over which the built-in HTTP server will serve the restful API
# requests. Default: 3000
port = 6969


# The telemetry section defines parameters for Hermes' built-in telemetry capabilities.
# https://hermes.informal.systems/telemetry.html
[telemetry]

# Whether or not to enable the telemetry service. Default: false
enabled = true

# Specify the IPv4/6 host over which the built-in HTTP server will serve the metrics
# gathered by the telemetry service. Default: 127.0.0.1
host = '127.0.0.1'

# Specify the port over which the built-in HTTP server will serve the metrics gathered
# by the telemetry service. Default: 3001
port = 9696


# This section specifies the filters for policy based relaying.
# Default: no policy/ filters
# The section is ignored if the global 'filter' option is set to 'false'.
# If the global 'filter' option is set to 'true' and this section is missing then no filtering is performed for this chain.
# Only packet filtering based on channel identifier can be specified.
# A channel filter has two fields:
# 1. `policy` - one of two types are supported:
#       - 'allow': permit relaying _only on_ the port/channel id in the list below,
#       - 'deny': permit relaying on any channel _except for_ the list below.
# 2. `list` - the list of channels specified by the port and channel identifiers.
#
# Example configuration of a channel filter, denying packet relaying on channel with port ID 'transfer' and channel ID 'channel-0':
#
# [chains.packet_filter]
# policy = 'deny'
# list = [
#   ['transfer', 'channel-0'],
# ]

[[chains]]
id = 'columbus-5'
rpc_addr = 'http://65.21.202.37:2161'
grpc_addr = 'http://65.21.202.37:2162'
websocket_addr = 'ws://65.21.202.37:2161/websocket'
rpc_timeout = '30s'
account_prefix = 'terra'
key_name = 'terra'
max_tx_size = 650000
store_prefix = 'ibc'
max_gas = 700000
gas_price = { price = 0.005, denom = 'uluna' }
gas_adjustment = 0.1
clock_drift ='5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
 ['transfer', 'channel-1'],
  ['transfer', 'channel-2'],
   ['transfer', 'channel-3']
   ]


#[[chains]]
#id = 'chihuahua-1'
#rpc_addr = 'http://127.0.0.1:2241'
#grpc_addr = 'http://127.0.0.1:2242'
#websocket_addr = 'ws://127.0.0.1:2241/websocket'
#rpc_timeout = '15s'
#account_prefix = 'chihuahua'
#key_name = 'chihuahua'
#store_prefix = 'ibc'
#max_tx_size = 450000
#max_gas = 1000000
#max_msg_num = 30
#gas_price = { price = 0.1, denom = 'uhuahua' }
#gas_adjustment = 1
#clock_drift ='15s'
#trusting_period = '14days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Delegate Notional Pls <3'


#[[chains]]
#id = 'arkh'
#rpc_addr = 'http://127.0.0.1:26657'
#grpc_addr = 'http://127.0.0.1:9090'
#websocket_addr = 'ws://127.0.0.1:26657/websocket'
#rpc_timeout = '15s'
#account_prefix = 'arkh'
#key_name = 'arkh'
#max_tx_size = 450000
#store_prefix = 'ibc'
#max_msg_num = 30
#max_gas = 872024
#gas_price = { price = 0.0011, denom = 'arkh' }
#gas_adjustment = 0.1
#clock_drift ='10s'
#trusting_period = '14days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Delegate Notional Pls <3'


#[[chains]]
#id = 'juno-1'
#rpc_addr = 'http://127.0.0.1:2071'
#grpc_addr = 'http://127.0.0.1:2072'
#websocket_addr = 'ws://127.0.0.1:2071/websocket'
#rpc_timeout = '15s'
#account_prefix = 'juno'
#key_name = 'juno'
#max_tx_size = 450000
#store_prefix = 'ibc'
#max_msg_num = 30
#max_gas = 8720240
#gas_price = { price = 0.0011, denom = 'ujuno' }
#gas_adjustment = 0.1
#clock_drift ='10s'
#trusting_period = '14days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Delegate Notional Pls <3'

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://127.0.0.1:2001'
websocket_addr = 'ws://127.0.0.1:2001/websocket'
grpc_addr = 'http://127.0.0.1:2002'
rpc_timeout = '30s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 15000000
max_msg_num = 10
gas_price = { price = 0.001, denom = 'uosmo' }
gas_adjustment = 1
clock_drift = '15s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'],['transfer', 'channel-42'],['transfer', 'channel-53'],['transfer', 'channel-1'],['transfer', 'channel-2'],['transfer', 'channel-3'],['transfer', 'channel-4'],['transfer', 'channel-5'],['transfer', 'channel-6'],['transfer', 'channel-7'],['transfer', 'channel-37'],['transfer', 'channel-38'],['transfer', 'channel-39'],['transfer', 'channel-15'],['transfer', 'channel-47'],['transfer', 'channel-51'],['transfer', 'channel-72'],['transfer', 'channel-77'],['transfer', 'channel-108'],['transfer', 'channel-81'],['transfer', 'channel-128']
 ]


[[chains]]
id = 'cheqd-mainnet-1'
rpc_addr = 'http://127.0.0.1:4021'
websocket_addr = 'ws://127.0.0.1:4021/websocket'
grpc_addr = 'http://127.0.0.1:4022'
max_tx_size = 180000
rpc_timeout = '30s'
account_prefix = 'cheqd'
key_name = 'cheqd'
store_prefix = 'ibc'
max_gas = 2000000
max_msg_num = 30
gas_price = { price = 25, denom = 'ncheq' }
gas_adjustment = 1
clock_drift = '15s'
trusting_period = '14days'





## craft testnet
#[[chains]]
#id = 'craft'
#rpc_addr = 'http://143.198.94.140:26657'
#websocket_addr = 'ws://143.198.94.140:26657/websocket'
#grpc_addr = 'http://143.198.94.140:9090'
#rpc_timeout = '15s'
#account_prefix = 'craft'
#key_name = 'craft'
#store_prefix = 'ibc'
#max_gas = 2000000
#max_msg_num = 30
#gas_price = { price = 0.001, denom = 'stake' }
#gas_adjustment = 1
#clock_drift = '15s'
#trusting_period = '14days'

#[[chains]]
#id = 'akashnet-2'
#rpc_addr = 'http://127.0.0.1:2021'
#websocket_addr = 'ws://127.0.0.1:2021/websocket'
#grpc_addr = 'http://127.0.0.1:2022'
#rpc_timeout = '15s'
#account_prefix = 'akash'
#key_name = 'akash'
#store_prefix = 'ibc'
#max_gas = 2000000
#max_msg_num = 30
#gas_price = { price = 0.001, denom = 'uakt' }
#gas_adjustment = 0.1
#clock_drift = '10s'
#trusting_period = '14days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Delegate Notional Pls <3'
#[chains.packet_filter]
#policy = 'allow'
#list = [
#   ['transfer', 'channel-17'],['transfer', 'channel-11'],['transfer', 'channel-23'],['transfer', 'channel-22'],['transfer', 'channel-20'],['transfer', 'channel-9'],['transfer', 'channel-18']
# ]

[[chains]]
id = 'sentinelhub-2'
rpc_addr = 'http://95.217.196.54:26657'
grpc_addr = 'http://95.217.196.54:9090'
websocket_addr = 'ws://95.217.196.54:26657/websocket'
account_prefix = 'sent'
rpc_timeout = '30s'
key_name = 'sentinel'
store_prefix = 'ibc'
max_gas = 2000000
max_msg_num = 30
gas_price = { price = 0.11, denom = 'udvpn' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0']
 ]



[[chains]]
id = 'irishub-1'
rpc_addr = 'http://127.0.0.1:2121'
grpc_addr = 'http://127.0.0.1:2122'
websocket_addr = 'ws://127.0.0.1:2121/websocket'
rpc_timeout = '30s'
account_prefix = 'iaa'
key_name = 'iris'
store_prefix = 'ibc'
max_gas = 2000000
max_tx_size = 1800000
gas_price = { price = 0.001, denom = 'uiris' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'


[[chains]]
id = 'dig-1'
rpc_addr = 'http://127.0.0.1:2391'
grpc_addr = 'http://127.0.0.1:2392'
websocket_addr = 'ws://127.0.0.1:2391/websocket'
rpc_timeout = '30s'
account_prefix = 'dig'
key_name = 'dig'
store_prefix = 'ibc'
max_gas = 5000000
max_tx_size = 500000
gas_price = { price = 0.002, denom = 'udig' }
gas_adjustment = 0.1
clock_drift ='5s'
trusting_period = '13days'
trust_threshold = { numerator = '1', denominator = '3' }


[[chains]]
id = 'regen-1'
rpc_addr = 'http://127.0.0.1:2061'
grpc_addr = 'http://127.0.0.1:2062'
websocket_addr = 'ws://127.0.0.1:2061/websocket'
account_prefix = 'regen'
rpc_timeout = '30s'
key_name = 'regen'
store_prefix = 'ibc'
max_msg_num = 30
max_gas = 2000000
max_tx_size = 180000
gas_price = { price = 0.001, denom = 'uregen' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'


[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http://127.0.0.1:2011'
grpc_addr = 'http://127.0.0.1:2012'
websocket_addr = 'ws://127.0.0.1:2011/websocket'
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_gas = 2000000
max_tx_size = 180000
max_msg_num = 20
gas_price = { price = 0.0011, denom = 'uatom' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'
[chains.packet_filter]
policy = 'allow'
list = [
	['transfer', 'channel-141'],['transfer', 'channel-182'],['transfer', 'channel-186'],['transfer', 'channel-190'],['transfer', 'channel-187'],['transfer', 'channel-202'],['transfer', 'channel-219'],['transfer', 'channel-223']
 ]



[[chains]]
id = 'emoney-3'
rpc_addr = 'http://127.0.0.1:2141'
grpc_addr = 'http://127.0.0.1:2142'
websocket_addr = 'ws://127.0.0.1:2141/websocket'
rpc_timeout = '30s'
account_prefix = 'emoney'
key_name = 'emoney'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 3000000
max_msg_num = 30
gas_price = { price = 0.1, denom = 'ungm' }
gas_adjustment = 1
clock_drift ='70s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'



[[chains]]
id = 'impacthub-3'
rpc_addr = 'http://127.0.0.1:2131'
grpc_addr = 'http://127.0.0.1:2132'
websocket_addr = 'ws://127.0.0.1:2131/websocket'
rpc_timeout = '30s'
account_prefix = 'ixo'
key_name = 'ixo'
max_tx_size = 450000
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.001, denom = 'uixo' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'


#[[chains]]
#id = 'iov-mainnet-ibc'
#rpc_addr = 'http://127.0.0.1:2171'
#grpc_addr = 'http://127.0.0.1:2172'
#websocket_addr = 'ws://127.0.0.1:2171/websocket'
#rpc_timeout = '15s'
#account_prefix = 'star'
#key_name = 'iov'
#max_tx_size = 450000
#store_prefix = 'ibc'
#max_gas = 8000000
#gas_price = { price = 2.0, denom = 'uiov' }
#gas_adjustment = 0.1
#clock_drift ='15s'
#trusting_period = '14days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Delegate Notional Pls <3'



#[[chains]]
#id = 'core-1'
#rpc_addr = 'http://65.21.202.37:2081'
#grpc_addr = 'http://65.21.202.37:2082'
#websocket_addr = 'ws://65.21.202.37:2081/websocket'
#rpc_timeout = '10s'
#account_prefix = 'persistence'
#key_name = 'persistence'
#store_prefix = 'ibc'
#max_gas = 2000000
#max_tx_size = 180000
#gas_price = { price = 0.001, denom = 'uxprt' }
#gas_adjustment = 0.1
#clock_drift ='15s'
#trusting_period = '14days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Delegate Notional Pls <3'
#[chains.packet_filter]
#policy = 'allow'
#list = [
#   ['transfer', 'channel-24'],['transfer', 'channel-26'],['transfer', 'channel-6']
# ]

#[[chains]]
#id = 'crypto-org-chain-mainnet-1'
#rpc_addr = 'http://127.0.0.1:2041'
#grpc_addr = 'http://127.0.0.1:2042'
#websocket_addr = 'ws://127.0.0.1:2041/websocket'
#rpc_timeout = '10s'
#account_prefix = 'cro'
#key_name = 'crypto'
#store_prefix = 'ibc'
#max_gas = 2000000
#max_tx_size = 450000
#gas_price = { price = 0.057, denom = 'basecro' }
#gas_adjustment = 0.1
#clock_drift ='15s'
#trusting_period = '14days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Delegate Notional Pls <3'
#[chains.packet_filter]
#policy = 'allow'
#list = [
#   ['transfer', 'channel-27'],['transfer', 'channel-23'],['transfer', 'channel-39'],['transfer', 'channel-21'],['transfer', 'channel-10'],['transfer', 'channel-33'],['transfer', 'channel-42']
# ]



[[chains]]
id = 'sifchain-1'
rpc_addr = 'http://127.0.0.1:2111'
grpc_addr = 'http://127.0.0.1:2112'
websocket_addr = 'ws://127.0.0.1:2111/websocket'
rpc_timeout = '30s'
account_prefix = 'sif'
key_name = 'sif'
store_prefix = 'ibc'
max_gas = 1000000000000000
gas_price = { price = 20000, denom = 'rowan' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'
[chains.packet_filter]
policy = 'allow'
list = [
	['transfer', 'channel-0'],['transfer', 'channel-17']
 ]


#[[chains]]
#id = 'bitcanna-1'
#rpc_addr = 'http://65.21.202.37:421'			
#grpc_addr = 'http://65.21.202.37:422'
#websocket_addr = 'ws://65.21.202.37:421/websocket'
#rpc_timeout = '15s'
#account_prefix = 'bcna'
#key_name = 'bcna'
#store_prefix = 'ibc'
#max_gas = 2000000
#gas_price = { price = 0.001, denom = 'ubcna' }
#gas_adjustment = 0.1
#clock_drift ='15s'
#trusting_period = '10days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Delegate Notional Pls <3'




[[chains]]
id = 'microtick-1'
rpc_addr = 'http://65.21.202.37:2151'
grpc_addr = 'http://65.21.202.37:2152'
websocket_addr = 'ws://65.21.202.37:2151/websocket'
rpc_timeout = '30s'
account_prefix = 'micro'
key_name = 'tick'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.001, denom = 'utick' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-16']
 ]


[[chains]]
id = 'likecoin-mainnet-2'
rpc_addr = 'http://65.21.202.37:2181'
grpc_addr = 'http://65.21.202.37:2182'
websocket_addr = 'ws://65.21.202.37:2181/websocket'
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'like'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 1.0, denom = 'nanolike' }
gas_adjustment = 1.0
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'


#[[chains]]
#id = 'stargaze-1'
#rpc_addr = 'http://127.0.0.1:2191'
#grpc_addr = 'http://127.0.0.1:2192'
#websocket_addr = 'ws://127.0.0.1:2191/websocket'
#rpc_timeout = '15s'
#account_prefix = 'stars'
#key_name = 'stargaze'
#store_prefix = 'ibc'
#max_gas = 2000000
#gas_price = { price = 1.0, denom = 'stars' }
#gas_adjustment = 1.0
#clock_drift = '10s'
#trusting_period = '7days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Delegate Notional Pls <3'


[[chains]]
id = 'kichain-2'
rpc_addr = 'http://127.0.0.1:2101'
grpc_addr = 'http://127.0.0.1:2102'
websocket_addr = 'ws://127.0.0.1:2101/websocket'
rpc_timeout = '30s'
account_prefix = 'ki'
key_name = 'ki'
store_prefix = 'ibc'
max_gas = 2000000
max_tx_size = 180000
max_msg_num = 20
gas_price = { price = 0.026, denom = 'uxki' }
gas_adjustment = 0.1
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Delegate Notional Pls <3'


#[[chains]]
#id = 'bostrom'
#rpc_addr = 'http://127.0.0.1:2051'
#grpc_addr = 'http://127.0.0.1:2052'
#websocket_addr = 'ws://127.0.0.1:2051/websocket'
#rpc_timeout = '15s'
#account_prefix = 'bostrom'
#key_name = 'cyber'
#store_prefix = 'ibc'
#max_gas = 2000000
#max_tx_size = 180000
#max_msg_num = 20
#gas_price = { price = 0.01, denom = 'boot' }
#gas_adjustment = 0.1
#clock_drift ='15s'
#trusting_period = '300000seconds'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Dyson Spheres and Space Pussy <3'

#[[chains]]
#id = 'laozi-mainnet'
#rpc_addr = 'http://127.0.0.1:2211'
#grpc_addr = 'http://127.0.0.1:2212'
#websocket_addr = 'ws://127.0.0.1:2211/websocket'
#rpc_timeout = '15s'
#account_prefix = 'band'
#key_name = 'band'
#store_prefix = 'ibc'
#max_gas = 2000000
#gas_price = { price = 0.001, denom = 'uband' }
#gas_adjustment = 1
#clock_drift = '15s'
#trusting_period = '7days'
#trust_threshold = { numerator = '1', denominator = '3' }
#memo_prefix = 'Delegate Notional Pls <3'

